name: Deploy
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            if [ ! -d "/home/app/jus_br_api/.git" ]; then
              git clone git@github.com:artur-devallus/jus_br_api.git /home/app/jus_br_api
              cd /home/app/jus_br_api
            else
              cd /home/app/jus_br_api
              git reset --hard
              git pull
            fi
            cat > .env << 'EOF'
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            JWT_ALGORITHM=HS256
            DATABASE_URL="mysql+pymysql://${{secrets.DB_NAME}}:${{secrets.DB_PASSWORD}}@${{secrets.DB_HOST}}:3306/${{secrets.DB_NAME}}"
            CELERY_BROKER_URL="redis://redis:6379/0"
            CELERY_RESULT_BACKEND="redis://redis:6379/0"
            TWO_CAPTCHA_KEY=${{secrets.TWO_CAPTCHA_KEY}}
            EOF
            
            docker compose build && docker compose up -d
